### ISSUE TITLE
Error in line breaking

### ISSUE THREAD

**Issue by victorlee** [adamvleggett/drawdown#1]
In order to break a line in html, one needs to break two lines in markdown.
Thus, between two text lines, there is an empty line with no texts.

Here is the problem, in the empty line, when there is a `SPACE` `U+0020` in the line, the two separate line breaks and becomes one.

Details:
- When the empty line is completely blank, the html results looks as it should be.
![](https://telegra.ph/file/2f1676e066f88b515e473.png)

- When there  is a SPACE in the supposedly empty line, the line in html breaks.
![](https://telegra.ph/file/82c6de450104ceb6d0697.png)

This issue is not observed in most other markdown converters online. Thanks.

**Comment by adamvleggett** [comment]
Fixed.
